- name: Next.js Export 🧪
      run: |
        bun run build
        echo "Checking directory structure:"
        ls -R  # ده هيطبع لنا كل الفولدرات اللي طلعت عشان نعرف الـ out فين!

    - name: Sync Capacitor 🔄
      run: |
        bun add -d @capacitor/cli @capacitor/android
        # هنجرب نغير الـ webDir لـ '.' عشان لو الملفات طلعت في الروت
        echo '{"appId": "com.lycans.fightclub", "appName": "Lycans Fight Club", "webDir": ".", "bundledWebRuntime": false}' > capacitor.config.json
        bunx cap sync
